# EDA: nq_open_gold

The goal here is to explore the gold standard dataset from the [Power of Noise](https://github.com/florin-git/The-Power-of-Noise)  \
The description is available [here](https://huggingface.co/datasets/florin-hf/nq_open_gold)  \
What will be the exploration:
- What are the column and size of the dataset?
- How to relate the gold document with the WikiDump2018?

In [8]:
import polars as pl
import os

## Load Datasets

In [3]:
PATH_NQ = "../data/nq_open"
train = pl.read_parquet(f"{PATH_NQ}/train-00000-of-00001.parquet")
dev = pl.read_parquet(f"{PATH_NQ}/validation-00000-of-00001.parquet")

In [4]:
train.head()

shape: (5, 2)
┌─────────────────────────────────┬──────────────────────────┐
│ question                        ┆ answer                   │
│ ---                             ┆ ---                      │
│ str                             ┆ list[str]                │
╞═════════════════════════════════╪══════════════════════════╡
│ where did they film hot tub ti… ┆ ["Fernie Alpine Resort"] │
│ who has the right of way in in… ┆ ["Neither vessel"]       │
│ who does annie work for attack… ┆ ["Marley"]               │
│ when was the immigration refor… ┆ ["November 6, 1986"]     │
│ when was puerto rico added to … ┆ ["1950"]                 │
└─────────────────────────────────┴──────────────────────────┘

In [5]:
dev.head()

shape: (5, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ question                        ┆ answer                          │
│ ---                             ┆ ---                             │
│ str                             ┆ list[str]                       │
╞═════════════════════════════════╪═════════════════════════════════╡
│ when was the last time anyone … ┆ ["14 December 1972 UTC", "Dece… │
│ who wrote he ain't heavy he's … ┆ ["Bobby Scott", "Bob Russell"]  │
│ how many seasons of the bastar… ┆ ["one", "one season"]           │
│ when did the eagles win last s… ┆ ["2017"]                        │
│ who won last year's ncaa women… ┆ ["South Carolina"]              │
└─────────────────────────────────┴─────────────────────────────────┘

## What are the sizes of the datasets?

In [6]:
len(train)

87925

In [7]:
len(dev)

3610

## Saving processed dataframes

In [11]:
PROCESSED_PATH = "../data/nq_open/processed"
os.makedirs(PROCESSED_PATH, exist_ok=True)
train.write_ipc(f"{PROCESSED_PATH}/train.feather")
dev.write_ipc(f"{PROCESSED_PATH}/dev.feather")

##