# EDA: nq_open_gold

The goal here is to explore the gold standard dataset from the [Power of Noise](https://github.com/florin-git/The-Power-of-Noise)  \
The description is available [here](https://huggingface.co/datasets/florin-hf/nq_open_gold)  \
What will be the exploration:
- What are the column and size of the dataset?
- How to relate the gold document with the WikiDump2018?

In [1]:
import polars as pl
import os

## Load Datasets

In [10]:
PATH_NQ = "../data/nq_open"
train = pl.read_parquet(f"{PATH_NQ}/train-00000-of-00001.parquet").with_row_index(name="idx").rename({"answer": "answers"})
dev = pl.read_parquet(f"{PATH_NQ}/validation-00000-of-00001.parquet").with_row_index(name="idx").rename({"answer": "answers"})

In [11]:
train.head()

shape: (5, 3)
┌─────┬─────────────────────────────────┬──────────────────────────┐
│ idx ┆ question                        ┆ answers                  │
│ --- ┆ ---                             ┆ ---                      │
│ u32 ┆ str                             ┆ list[str]                │
╞═════╪═════════════════════════════════╪══════════════════════════╡
│ 0   ┆ where did they film hot tub ti… ┆ ["Fernie Alpine Resort"] │
│ 1   ┆ who has the right of way in in… ┆ ["Neither vessel"]       │
│ 2   ┆ who does annie work for attack… ┆ ["Marley"]               │
│ 3   ┆ when was the immigration refor… ┆ ["November 6, 1986"]     │
│ 4   ┆ when was puerto rico added to … ┆ ["1950"]                 │
└─────┴─────────────────────────────────┴──────────────────────────┘

In [12]:
dev.head()

shape: (5, 3)
┌─────┬─────────────────────────────────┬─────────────────────────────────┐
│ idx ┆ question                        ┆ answers                         │
│ --- ┆ ---                             ┆ ---                             │
│ u32 ┆ str                             ┆ list[str]                       │
╞═════╪═════════════════════════════════╪═════════════════════════════════╡
│ 0   ┆ when was the last time anyone … ┆ ["14 December 1972 UTC", "Dece… │
│ 1   ┆ who wrote he ain't heavy he's … ┆ ["Bobby Scott", "Bob Russell"]  │
│ 2   ┆ how many seasons of the bastar… ┆ ["one", "one season"]           │
│ 3   ┆ when did the eagles win last s… ┆ ["2017"]                        │
│ 4   ┆ who won last year's ncaa women… ┆ ["South Carolina"]              │
└─────┴─────────────────────────────────┴─────────────────────────────────┘

## What are the sizes of the datasets?

In [13]:
len(train)

87925

In [14]:
len(dev)

3610

## Saving processed dataframes

In [15]:
PROCESSED_PATH = "../data/nq_open/processed"
os.makedirs(PROCESSED_PATH, exist_ok=True)
train.write_ipc(f"{PROCESSED_PATH}/train.feather")
dev.write_ipc(f"{PROCESSED_PATH}/dev.feather")

##